"""tg_id big-int

Revision ID: 7119ab95cc6e
Revises: f692bda74460
Create Date: 2025-12-18 01:55:31.793412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7119ab95cc6e'
down_revision: Union[str, Sequence[str], None] = 'f692bda74460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bets', ['uuid'])
    op.create_unique_constraint(None, 'game_outcome_settings', ['uuid'])
    op.create_unique_constraint(None, 'payouts', ['uuid'])
    op.alter_column('users', 'tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'tg_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'payouts', type_='unique')
    op.drop_constraint(None, 'game_outcome_settings', type_='unique')
    op.drop_constraint(None, 'bets', type_='unique')
    # ### end Alembic commands ###
