"""Initial tables

Revision ID: 89172e887050
Revises: 
Create Date: 2025-12-21 02:00:05.055117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89172e887050'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_outcome_settings',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('game_code', sa.Enum('SLOT', 'BOWLING', 'BASKETBALL', 'FOOTBALL', 'DICE', 'DARTS', name='gamecode'), nullable=False),
    sa.Column('outcome_code', sa.Enum('LOSE', 'WIN', 'JACKPOT', name='outcomecode'), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('stars_balance', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('tg_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('bets',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('game_code', sa.Enum('SLOT', 'BOWLING', 'BASKETBALL', 'FOOTBALL', 'DICE', 'DARTS', name='gamecode'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', name='betstatus'), nullable=False),
    sa.Column('telegram_transaction_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('game_rounds',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('bet_uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('game_code', sa.Enum('SLOT', 'BOWLING', 'BASKETBALL', 'FOOTBALL', 'DICE', 'DARTS', name='gamecode'), nullable=False),
    sa.Column('outcome_code', sa.Enum('LOSE', 'WIN', 'JACKPOT', name='outcomecode'), nullable=False),
    sa.Column('is_win', sa.Boolean(), nullable=False),
    sa.Column('win_amount', sa.Integer(), nullable=False),
    sa.Column('seed', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bet_uuid'], ['bets.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('bet_uuid')
    )
    op.create_table('payouts',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('game_round_uuid', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='payoutstatus'), nullable=False),
    sa.Column('telegram_payout_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_round_uuid'], ['game_rounds.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('game_round_uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payouts')
    op.drop_table('game_rounds')
    op.drop_table('bets')
    op.drop_table('users')
    op.drop_table('game_outcome_settings')
    # ### end Alembic commands ###
